name: Test Multi-Arch Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dev-node:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      context: ./base
      platforms: linux/amd64,linux/arm64
      output: image
      push: true
      meta-images: ${{ github.repository_owner }}/dev-node
      meta-tags: type=raw,value=v4-test
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        - registry: dhi.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
